import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "@/config/fontawesome";
import "./globals.css";

const JosefinSans = Josefin_Sans({
  subsets: ["latin-ext"],
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`overflow-hidden ${JosefinSans.className}`}>
      <body className="text-[1.1rem]">{children}</body>
    </html>
  );
}
