import type { Metadata } from "next";
import { Theme } from "@radix-ui/themes";
import MainLayout from "@/layouts/main/layout";
import "@/config/fontawesome";
import "./globals.css";
import "@radix-ui/themes/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
